appName: frontend
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.3.8
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: CHECKOUT_SERVICE_ADDR
  value: "checkoutservice:5050"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: AD_SERVICE_ADDR
  value: "adservice:9555"
- name: RECOMMENDATION_SERVICE_ADDR
  value: "recommendationservice:8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 80
serviceType: LoadBalancer