appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.3.8
appReplicas: 2
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 3550